// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jplgtzhbdiajlrrwurqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwbGd0emhiZGlhamxycnd1cnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjczNjcsImV4cCI6MjA3MjQwMzM2N30.Z0vcW3P91a5hptlO7nEFxD-tXuIr6t4l3f9hYIaEkGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});